// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

public struct AutoMlVideoObjectTrackingInputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var modelType: AutoMlVideoObjectTrackingInputs.ModelType =
    AutoMlVideoObjectTrackingInputs.ModelType()

  /// Initialize a new instance of `AutoMlVideoObjectTrackingInputs`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoMlVideoObjectTrackingInputs().with { $0.modelType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum ModelType: Codable, Equatable, Sendable {
    /// Should not be set.
    case unspecified
    /// A model best tailored to be used within Google Cloud, and which c annot
    /// be exported. Default.
    case cloud
    /// A model that, in addition to being available within Google Cloud, can
    /// also be exported (see ModelService.ExportModel) as a TensorFlow or
    /// TensorFlow Lite model and used on a mobile or edge device afterwards.
    case mobileVersatile1
    /// A versatile model that is meant to be exported (see
    /// ModelService.ExportModel) and used on a Google Coral device.
    case mobileCoralVersatile1
    /// A model that trades off quality for low latency, to be exported (see
    /// ModelService.ExportModel) and used on a Google Coral device.
    case mobileCoralLowLatency1
    /// A versatile model that is meant to be exported (see
    /// ModelService.ExportModel) and used on an NVIDIA Jetson device.
    case mobileJetsonVersatile1
    /// A model that trades off quality for low latency, to be exported (see
    /// ModelService.ExportModel) and used on an NVIDIA Jetson device.
    case mobileJetsonLowLatency1
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloud: return 1
      case .mobileVersatile1: return 2
      case .mobileCoralVersatile1: return 3
      case .mobileCoralLowLatency1: return 4
      case .mobileJetsonVersatile1: return 5
      case .mobileJetsonLowLatency1: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
      case .cloud: return "CLOUD"
      case .mobileVersatile1: return "MOBILE_VERSATILE_1"
      case .mobileCoralVersatile1: return "MOBILE_CORAL_VERSATILE_1"
      case .mobileCoralLowLatency1: return "MOBILE_CORAL_LOW_LATENCY_1"
      case .mobileJetsonVersatile1: return "MOBILE_JETSON_VERSATILE_1"
      case .mobileJetsonLowLatency1: return "MOBILE_JETSON_LOW_LATENCY_1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD": self = .cloud
      case "MOBILE_VERSATILE_1": self = .mobileVersatile1
      case "MOBILE_CORAL_VERSATILE_1": self = .mobileCoralVersatile1
      case "MOBILE_CORAL_LOW_LATENCY_1": self = .mobileCoralLowLatency1
      case "MOBILE_JETSON_VERSATILE_1": self = .mobileJetsonVersatile1
      case "MOBILE_JETSON_LOW_LATENCY_1": self = .mobileJetsonLowLatency1
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloud
      case 2: self = .mobileVersatile1
      case 3: self = .mobileCoralVersatile1
      case 4: self = .mobileCoralLowLatency1
      case 5: self = .mobileJetsonVersatile1
      case 6: self = .mobileJetsonLowLatency1
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloud: return try container.encode(1)
      case .mobileVersatile1: return try container.encode(2)
      case .mobileCoralVersatile1: return try container.encode(3)
      case .mobileCoralLowLatency1: return try container.encode(4)
      case .mobileJetsonVersatile1: return try container.encode(5)
      case .mobileJetsonLowLatency1: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlVideoObjectTrackingInputs"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
