// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct AutoMlTextSentimentInputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A sentiment is expressed as an integer ordinal, where higher value
  /// means a more positive sentiment. The range of sentiments that will be used
  /// is between 0 and sentimentMax (inclusive on both ends), and all the values
  /// in the range must be represented in the dataset before a model can be
  /// created.
  /// Only the Annotations with this sentimentMax will be used for training.
  /// sentimentMax value must be between 1 and 10 (inclusive).
  public var sentimentMax: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `AutoMlTextSentimentInputs`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoMlTextSentimentInputs().with { $0.sentimentMax = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTextSentimentInputs"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
