// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct AutoMlImageObjectDetectionInputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var modelType: AutoMlImageObjectDetectionInputs.ModelType =
    AutoMlImageObjectDetectionInputs.ModelType()

  /// The training budget of creating this model, expressed in milli node
  /// hours i.e. 1,000 value in this field means 1 node hour. The actual
  /// metadata.costMilliNodeHours will be equal or less than this value.
  /// If further model training ceases to provide any improvements, it will
  /// stop without using the full budget and the metadata.successfulStopReason
  /// will be `model-converged`.
  /// Note, node_hour  = actual_hour * number_of_nodes_involved.
  /// For modelType `cloud`(default), the budget must be between 20,000
  /// and 900,000 milli node hours, inclusive. The default value is 216,000
  /// which represents one day in wall time, considering 9 nodes are used.
  /// For model types `mobile-tf-low-latency-1`, `mobile-tf-versatile-1`,
  /// `mobile-tf-high-accuracy-1`
  /// the training budget must be between 1,000 and 100,000 milli node hours,
  /// inclusive. The default value is 24,000 which represents one day in
  /// wall time on a single node that is used.
  public var budgetMilliNodeHours: Swift.Int64 = Swift.Int64()

  /// Use the entire training budget. This disables the early stopping feature.
  /// When false the early stopping feature is enabled, which means that AutoML
  /// Image Object Detection might stop training before the entire training
  /// budget has been used.
  public var disableEarlyStopping: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `AutoMlImageObjectDetectionInputs`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoMlImageObjectDetectionInputs().with { $0.modelType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum ModelType: Codable, Equatable, Sendable {
    /// Should not be set.
    case unspecified
    /// A model best tailored to be used within Google Cloud, and which cannot
    /// be exported. Expected to have a higher latency, but should also have a
    /// higher prediction quality than other cloud models.
    case cloudHighAccuracy1
    /// A model best tailored to be used within Google Cloud, and which cannot
    /// be exported. Expected to have a low latency, but may have lower
    /// prediction quality than other cloud models.
    case cloudLowLatency1
    /// A model that, in addition to being available within Google
    /// Cloud can also be exported (see ModelService.ExportModel) and
    /// used on a mobile or edge device with TensorFlow afterwards.
    /// Expected to have low latency, but may have lower prediction
    /// quality than other mobile models.
    case mobileTfLowLatency1
    /// A model that, in addition to being available within Google
    /// Cloud can also be exported (see ModelService.ExportModel) and
    /// used on a mobile or edge device with TensorFlow afterwards.
    case mobileTfVersatile1
    /// A model that, in addition to being available within Google
    /// Cloud, can also be exported (see ModelService.ExportModel) and
    /// used on a mobile or edge device with TensorFlow afterwards.
    /// Expected to have a higher latency, but should also have a higher
    /// prediction quality than other mobile models.
    case mobileTfHighAccuracy1
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudHighAccuracy1: return 1
      case .cloudLowLatency1: return 2
      case .mobileTfLowLatency1: return 3
      case .mobileTfVersatile1: return 4
      case .mobileTfHighAccuracy1: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
      case .cloudHighAccuracy1: return "CLOUD_HIGH_ACCURACY_1"
      case .cloudLowLatency1: return "CLOUD_LOW_LATENCY_1"
      case .mobileTfLowLatency1: return "MOBILE_TF_LOW_LATENCY_1"
      case .mobileTfVersatile1: return "MOBILE_TF_VERSATILE_1"
      case .mobileTfHighAccuracy1: return "MOBILE_TF_HIGH_ACCURACY_1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_HIGH_ACCURACY_1": self = .cloudHighAccuracy1
      case "CLOUD_LOW_LATENCY_1": self = .cloudLowLatency1
      case "MOBILE_TF_LOW_LATENCY_1": self = .mobileTfLowLatency1
      case "MOBILE_TF_VERSATILE_1": self = .mobileTfVersatile1
      case "MOBILE_TF_HIGH_ACCURACY_1": self = .mobileTfHighAccuracy1
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudHighAccuracy1
      case 2: self = .cloudLowLatency1
      case 3: self = .mobileTfLowLatency1
      case 4: self = .mobileTfVersatile1
      case 5: self = .mobileTfHighAccuracy1
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudHighAccuracy1: return try container.encode(1)
      case .cloudLowLatency1: return try container.encode(2)
      case .mobileTfLowLatency1: return try container.encode(3)
      case .mobileTfVersatile1: return try container.encode(4)
      case .mobileTfHighAccuracy1: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlImageObjectDetectionInputs"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
