// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct AutoMlImageSegmentationInputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var modelType: AutoMlImageSegmentationInputs.ModelType =
    AutoMlImageSegmentationInputs.ModelType()

  /// The training budget of creating this model, expressed in milli node
  /// hours i.e. 1,000 value in this field means 1 node hour. The actual
  /// metadata.costMilliNodeHours will be equal or less than this value.
  /// If further model training ceases to provide any improvements, it will
  /// stop without using the full budget and the metadata.successfulStopReason
  /// will be `model-converged`.
  /// Note, node_hour  = actual_hour * number_of_nodes_involved. Or
  /// actaul_wall_clock_hours = train_budget_milli_node_hours /
  ///                           (number_of_nodes_involved * 1000)
  /// For modelType `cloud-high-accuracy-1`(default), the budget must be between
  /// 20,000 and 2,000,000 milli node hours, inclusive. The default value is
  /// 192,000 which represents one day in wall time
  /// (1000 milli * 24 hours * 8 nodes).
  public var budgetMilliNodeHours: Swift.Int64 = Swift.Int64()

  /// The ID of the `base` model. If it is specified, the new model will be
  /// trained based on the `base` model. Otherwise, the new model will be
  /// trained from scratch. The `base` model must be in the same
  /// Project and Location as the new Model to train, and have the same
  /// modelType.
  public var baseModelId: Swift.String = Swift.String()

  /// Initialize a new instance of `AutoMlImageSegmentationInputs`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoMlImageSegmentationInputs().with { $0.modelType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum ModelType: Codable, Equatable, Sendable {
    /// Should not be set.
    case unspecified
    /// A model to be used via prediction calls to uCAIP API. Expected
    /// to have a higher latency, but should also have a higher prediction
    /// quality than other models.
    case cloudHighAccuracy1
    /// A model to be used via prediction calls to uCAIP API. Expected
    /// to have a lower latency but relatively lower prediction quality.
    case cloudLowAccuracy1
    /// A model that, in addition to being available within Google
    /// Cloud, can also be exported (see ModelService.ExportModel) as TensorFlow
    /// model and used on a mobile or edge device afterwards.
    /// Expected to have low latency, but may have lower prediction
    /// quality than other mobile models.
    case mobileTfLowLatency1
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudHighAccuracy1: return 1
      case .cloudLowAccuracy1: return 2
      case .mobileTfLowLatency1: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
      case .cloudHighAccuracy1: return "CLOUD_HIGH_ACCURACY_1"
      case .cloudLowAccuracy1: return "CLOUD_LOW_ACCURACY_1"
      case .mobileTfLowLatency1: return "MOBILE_TF_LOW_LATENCY_1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_HIGH_ACCURACY_1": self = .cloudHighAccuracy1
      case "CLOUD_LOW_ACCURACY_1": self = .cloudLowAccuracy1
      case "MOBILE_TF_LOW_LATENCY_1": self = .mobileTfLowLatency1
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudHighAccuracy1
      case 2: self = .cloudLowAccuracy1
      case 3: self = .mobileTfLowLatency1
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudHighAccuracy1: return try container.encode(1)
      case .cloudLowAccuracy1: return try container.encode(2)
      case .mobileTfLowLatency1: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlImageSegmentationInputs"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
