// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct AutoMlTablesInputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of prediction the Model is to produce.
  ///   "classification" - Predict one out of multiple target values is
  ///                      picked for each row.
  ///   "regression" - Predict a value based on its relation to other values.
  ///                  This type is available only to columns that contain
  ///                  semantically numeric values, i.e. integers or floating
  ///                  point number, even if stored as e.g. strings.
  public var predictionType: Swift.String = Swift.String()

  /// The column name of the target column that the model is to predict.
  public var targetColumn: Swift.String = Swift.String()

  /// Each transformation will apply transform function to given input column.
  /// And the result will be used for training.
  /// When creating transformation for BigQuery Struct column, the column should
  /// be flattened using "." as the delimiter.
  public var transformations: [AutoMlTablesInputs.Transformation] = []

  /// Objective function the model is optimizing towards. The training process
  /// creates a model that maximizes/minimizes the value of the objective
  /// function over the validation set.
  ///
  /// The supported optimization objectives depend on the prediction type.
  /// If the field is not set, a default objective function is used.
  ///
  /// classification (binary):
  ///   "maximize-au-roc" (default) - Maximize the area under the receiver
  ///                                 operating characteristic (ROC) curve.
  ///   "minimize-log-loss" - Minimize log loss.
  ///   "maximize-au-prc" - Maximize the area under the precision-recall curve.
  ///   "maximize-precision-at-recall" - Maximize precision for a specified
  ///                                   recall value.
  ///   "maximize-recall-at-precision" - Maximize recall for a specified
  ///                                    precision value.
  ///
  /// classification (multi-class):
  ///   "minimize-log-loss" (default) - Minimize log loss.
  ///
  /// regression:
  ///   "minimize-rmse" (default) - Minimize root-mean-squared error (RMSE).
  ///   "minimize-mae" - Minimize mean-absolute error (MAE).
  ///   "minimize-rmsle" - Minimize root-mean-squared log error (RMSLE).
  public var optimizationObjective: Swift.String = Swift.String()

  /// Required. The train budget of creating this model, expressed in milli node
  /// hours i.e. 1,000 value in this field means 1 node hour.
  ///
  /// The training cost of the model will not exceed this budget. The final cost
  /// will be attempted to be close to the budget, though may end up being (even)
  /// noticeably smaller - at the backend's discretion. This especially may
  /// happen when further model training ceases to provide any improvements.
  ///
  /// If the budget is set to a value known to be insufficient to train a
  /// model for the given dataset, the training won't be attempted and
  /// will error.
  ///
  /// The train budget must be between 1,000 and 72,000 milli node hours,
  /// inclusive.
  public var trainBudgetMilliNodeHours: Swift.Int64 = Swift.Int64()

  /// Use the entire training budget. This disables the early stopping feature.
  /// By default, the early stopping feature is enabled, which means that AutoML
  /// Tables might stop training before the entire training budget has been used.
  public var disableEarlyStopping: Swift.Bool = Swift.Bool()

  /// Column name that should be used as the weight column.
  /// Higher values in this column give more importance to the row
  /// during model training. The column must have numeric values between 0 and
  /// 10000 inclusively; 0 means the row is ignored for training. If weight
  /// column field is not set, then all rows are assumed to have equal weight
  /// of 1.
  public var weightColumnName: Swift.String = Swift.String()

  /// Configuration for exporting test set predictions to a BigQuery table. If
  /// this configuration is absent, then the export is not performed.
  public var exportEvaluatedDataItemsConfig: ExportEvaluatedDataItemsConfig? = nil

  /// Additional experiment flags for the Tables training pipeline.
  public var additionalExperiments: [Swift.String] = []

  /// Additional optimization objective configuration. Required for
  /// `maximize-precision-at-recall` and `maximize-recall-at-precision`,
  /// otherwise unused.
  public var additionalOptimizationObjectiveConfig: OneOf_AdditionalOptimizationObjectiveConfig? =
    nil

  /// Initialize a new instance of `AutoMlTablesInputs`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoMlTablesInputs().with { $0.optimizationObjectiveRecallValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case optimizationObjectiveRecallValue = "optimizationObjectiveRecallValue"
    case optimizationObjectivePrecisionValue = "optimizationObjectivePrecisionValue"
    case predictionType = "predictionType"
    case targetColumn = "targetColumn"
    case transformations = "transformations"
    case optimizationObjective = "optimizationObjective"
    case trainBudgetMilliNodeHours = "trainBudgetMilliNodeHours"
    case disableEarlyStopping = "disableEarlyStopping"
    case weightColumnName = "weightColumnName"
    case exportEvaluatedDataItemsConfig = "exportEvaluatedDataItemsConfig"
    case additionalExperiments = "additionalExperiments"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.predictionType = try container.decode(Swift.String.self, forKey: .predictionType)
    self.targetColumn = try container.decode(Swift.String.self, forKey: .targetColumn)
    self.transformations = try container.decode(
      [AutoMlTablesInputs.Transformation].self, forKey: .transformations)
    self.optimizationObjective = try container.decode(
      Swift.String.self, forKey: .optimizationObjective)
    self.trainBudgetMilliNodeHours = try container.decode(
      Swift.Int64.self, forKey: .trainBudgetMilliNodeHours)
    self.disableEarlyStopping = try container.decode(Swift.Bool.self, forKey: .disableEarlyStopping)
    self.weightColumnName = try container.decode(Swift.String.self, forKey: .weightColumnName)
    self.exportEvaluatedDataItemsConfig = try container.decodeIfPresent(
      ExportEvaluatedDataItemsConfig.self, forKey: .exportEvaluatedDataItemsConfig)
    self.additionalExperiments = try container.decode(
      [Swift.String].self, forKey: .additionalExperiments)

    var additionalOptimizationObjectiveConfig: OneOf_AdditionalOptimizationObjectiveConfig? = nil
    let additionalOptimizationObjectiveConfigCheckAndSet = {
      if additionalOptimizationObjectiveConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription:
              "Multiple values set for oneof 'additionalOptimizationObjectiveConfig'"))
      }
      additionalOptimizationObjectiveConfig = $0
    }
    if let optimizationObjectiveRecallValue = try container.decodeIfPresent(
      Swift.Float.self, forKey: .optimizationObjectiveRecallValue)
    {
      try additionalOptimizationObjectiveConfigCheckAndSet(
        .optimizationObjectiveRecallValue(optimizationObjectiveRecallValue))
    }
    if let optimizationObjectivePrecisionValue = try container.decodeIfPresent(
      Swift.Float.self, forKey: .optimizationObjectivePrecisionValue)
    {
      try additionalOptimizationObjectiveConfigCheckAndSet(
        .optimizationObjectivePrecisionValue(optimizationObjectivePrecisionValue))
    }
    self.additionalOptimizationObjectiveConfig = additionalOptimizationObjectiveConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.predictionType, forKey: .predictionType)
    try container.encode(self.targetColumn, forKey: .targetColumn)
    try container.encode(self.transformations, forKey: .transformations)
    try container.encode(self.optimizationObjective, forKey: .optimizationObjective)
    try container.encode(self.trainBudgetMilliNodeHours, forKey: .trainBudgetMilliNodeHours)
    try container.encode(self.disableEarlyStopping, forKey: .disableEarlyStopping)
    try container.encode(self.weightColumnName, forKey: .weightColumnName)
    try container.encode(
      self.exportEvaluatedDataItemsConfig, forKey: .exportEvaluatedDataItemsConfig)
    try container.encode(self.additionalExperiments, forKey: .additionalExperiments)

    if let choice = self.additionalOptimizationObjectiveConfig {
      switch choice {
      case .optimizationObjectiveRecallValue(let value):
        try container.encode(value, forKey: .optimizationObjectiveRecallValue)
      case .optimizationObjectivePrecisionValue(let value):
        try container.encode(value, forKey: .optimizationObjectivePrecisionValue)
      }
    }
  }

  public struct Transformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The transformation that the training pipeline will apply to the input
    /// columns.
    public var transformationDetail: OneOf_TransformationDetail? = nil

    /// Initialize a new instance of `Transformation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Transformation().with { $0.auto = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case auto = "auto"
      case numeric = "numeric"
      case categorical = "categorical"
      case timestamp = "timestamp"
      case text = "text"
      case repeatedNumeric = "repeatedNumeric"
      case repeatedCategorical = "repeatedCategorical"
      case repeatedText = "repeatedText"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var transformationDetail: OneOf_TransformationDetail? = nil
      let transformationDetailCheckAndSet = {
        if transformationDetail != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'transformationDetail'"))
        }
        transformationDetail = $0
      }
      if let auto = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.AutoTransformation?.self, forKey: .auto)
      {
        try transformationDetailCheckAndSet(.auto(auto))
      }
      if let numeric = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.NumericTransformation?.self, forKey: .numeric)
      {
        try transformationDetailCheckAndSet(.numeric(numeric))
      }
      if let categorical = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.CategoricalTransformation?.self, forKey: .categorical)
      {
        try transformationDetailCheckAndSet(.categorical(categorical))
      }
      if let timestamp = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.TimestampTransformation?.self, forKey: .timestamp)
      {
        try transformationDetailCheckAndSet(.timestamp(timestamp))
      }
      if let text = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.TextTransformation?.self, forKey: .text)
      {
        try transformationDetailCheckAndSet(.text(text))
      }
      if let repeatedNumeric = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.NumericArrayTransformation?.self, forKey: .repeatedNumeric
      ) {
        try transformationDetailCheckAndSet(.repeatedNumeric(repeatedNumeric))
      }
      if let repeatedCategorical = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.CategoricalArrayTransformation?.self,
        forKey: .repeatedCategorical)
      {
        try transformationDetailCheckAndSet(.repeatedCategorical(repeatedCategorical))
      }
      if let repeatedText = try container.decodeIfPresent(
        AutoMlTablesInputs.Transformation.TextArrayTransformation?.self, forKey: .repeatedText)
      {
        try transformationDetailCheckAndSet(.repeatedText(repeatedText))
      }
      self.transformationDetail = transformationDetail
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.transformationDetail {
        switch choice {
        case .auto(let value):
          try container.encode(value, forKey: .auto)
        case .numeric(let value):
          try container.encode(value, forKey: .numeric)
        case .categorical(let value):
          try container.encode(value, forKey: .categorical)
        case .timestamp(let value):
          try container.encode(value, forKey: .timestamp)
        case .text(let value):
          try container.encode(value, forKey: .text)
        case .repeatedNumeric(let value):
          try container.encode(value, forKey: .repeatedNumeric)
        case .repeatedCategorical(let value):
          try container.encode(value, forKey: .repeatedCategorical)
        case .repeatedText(let value):
          try container.encode(value, forKey: .repeatedText)
        }
      }
    }

    /// Training pipeline will infer the proper transformation based on the
    /// statistic of dataset.
    public struct AutoTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// Initialize a new instance of `AutoTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AutoTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.AutoTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Training pipeline will perform following transformation functions.
    /// *  The value converted to float32.
    /// *  The z_score of the value.
    /// *  log(value+1) when the value is greater than or equal to 0. Otherwise,
    ///    this transformation is not applied and the value is considered a
    ///    missing value.
    /// *  z_score of log(value+1) when the value is greater than or equal to 0.
    ///    Otherwise, this transformation is not applied and the value is
    ///    considered a missing value.
    /// *  A boolean value that indicates whether the value is valid.
    public struct NumericTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// If invalid values is allowed, the training pipeline will create a
      /// boolean feature that indicated whether the value is valid.
      /// Otherwise, the training pipeline will discard the input row from
      /// trainining data.
      public var invalidValuesAllowed: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `NumericTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NumericTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.NumericTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Training pipeline will perform following transformation functions.
    /// *  The categorical string as is--no change to case, punctuation,
    /// spelling,
    ///    tense, and so on.
    /// *  Convert the category name to a dictionary lookup index and generate an
    ///    embedding for each index.
    /// *  Categories that appear less than 5 times in the training dataset are
    ///    treated as the "unknown" category. The "unknown" category gets its own
    ///    special lookup index and resulting embedding.
    public struct CategoricalTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// Initialize a new instance of `CategoricalTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CategoricalTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.CategoricalTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Training pipeline will perform following transformation functions.
    /// *  Apply the transformation functions for Numerical columns.
    /// *  Determine the year, month, day,and weekday. Treat each value from the
    /// *  timestamp as a Categorical column.
    /// *  Invalid numerical values (for example, values that fall outside of a
    ///    typical timestamp range, or are extreme values) receive no special
    ///    treatment and are not removed.
    public struct TimestampTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// The format in which that time field is expressed. The time_format must
      /// either be one of:
      /// * `unix-seconds`
      /// * `unix-milliseconds`
      /// * `unix-microseconds`
      /// * `unix-nanoseconds`
      /// (for respectively number of seconds, milliseconds, microseconds and
      /// nanoseconds since start of the Unix epoch);
      /// or be written in `strftime` syntax. If time_format is not set, then the
      /// default format is RFC 3339 `date-time` format, where
      /// `time-offset` = `"Z"` (e.g. 1985-04-12T23:20:50.52Z)
      public var timeFormat: Swift.String = Swift.String()

      /// If invalid values is allowed, the training pipeline will create a
      /// boolean feature that indicated whether the value is valid.
      /// Otherwise, the training pipeline will discard the input row from
      /// trainining data.
      public var invalidValuesAllowed: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `TimestampTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TimestampTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.TimestampTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Training pipeline will perform following transformation functions.
    /// *  The text as is--no change to case, punctuation, spelling, tense, and
    /// so
    ///    on.
    /// *  Tokenize text to words. Convert each words to a dictionary lookup
    /// index
    ///    and generate an embedding for each index. Combine the embedding of all
    ///    elements into a single embedding using the mean.
    /// *  Tokenization is based on unicode script boundaries.
    /// *  Missing values get their own lookup index and resulting embedding.
    /// *  Stop-words receive no special treatment and are not removed.
    public struct TextTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// Initialize a new instance of `TextTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TextTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.TextTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Treats the column as numerical array and performs following
    /// transformation functions.
    /// *  All transformations for Numerical types applied to the average of the
    ///    all elements.
    /// *  The average of empty arrays is treated as zero.
    public struct NumericArrayTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// If invalid values is allowed, the training pipeline will create a
      /// boolean feature that indicated whether the value is valid.
      /// Otherwise, the training pipeline will discard the input row from
      /// trainining data.
      public var invalidValuesAllowed: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `NumericArrayTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NumericArrayTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.NumericArrayTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Treats the column as categorical array and performs following
    /// transformation functions.
    /// *  For each element in the array, convert the category name to a
    /// dictionary
    ///    lookup index and generate an embedding for each index.
    ///    Combine the embedding of all elements into a single embedding using
    ///    the mean.
    /// *  Empty arrays treated as an embedding of zeroes.
    public struct CategoricalArrayTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// Initialize a new instance of `CategoricalArrayTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CategoricalArrayTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.CategoricalArrayTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Treats the column as text array and performs following transformation
    /// functions.
    /// *  Concatenate all text values in the array into a single text value
    /// using
    ///    a space (" ") as a delimiter, and then treat the result as a single
    ///    text value. Apply the transformations for Text columns.
    /// *  Empty arrays treated as an empty text.
    public struct TextArrayTransformation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var columnName: Swift.String = Swift.String()

      /// Initialize a new instance of `TextArrayTransformation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TextArrayTransformation().with { $0.columnName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation.TextArrayTransformation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The transformation that the training pipeline will apply to the input
    /// columns.
    public enum OneOf_TransformationDetail: Codable, Equatable, Sendable {
      indirect case auto(AutoMlTablesInputs.Transformation.AutoTransformation?)
      indirect case numeric(AutoMlTablesInputs.Transformation.NumericTransformation?)
      indirect case categorical(AutoMlTablesInputs.Transformation.CategoricalTransformation?)
      indirect case timestamp(AutoMlTablesInputs.Transformation.TimestampTransformation?)
      indirect case text(AutoMlTablesInputs.Transformation.TextTransformation?)
      indirect case repeatedNumeric(AutoMlTablesInputs.Transformation.NumericArrayTransformation?)
      indirect case repeatedCategorical(
        AutoMlTablesInputs.Transformation.CategoricalArrayTransformation?)
      indirect case repeatedText(AutoMlTablesInputs.Transformation.TextArrayTransformation?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs.Transformation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Additional optimization objective configuration. Required for
  /// `maximize-precision-at-recall` and `maximize-recall-at-precision`,
  /// otherwise unused.
  public enum OneOf_AdditionalOptimizationObjectiveConfig: Codable, Equatable, Sendable {
    /// Required when optimization_objective is "maximize-precision-at-recall".
    /// Must be between 0 and 1, inclusive.
    case optimizationObjectiveRecallValue(Swift.Float)
    /// Required when optimization_objective is "maximize-recall-at-precision".
    /// Must be between 0 and 1, inclusive.
    case optimizationObjectivePrecisionValue(Swift.Float)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.AutoMlTablesInputs"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
