// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for exporting test set predictions to a BigQuery table.
public struct ExportEvaluatedDataItemsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// URI of desired destination BigQuery table. Expected format:
  /// bq://<project_id>:<dataset_id>:<table>
  ///
  /// If not specified, then results are exported to the following auto-created
  /// BigQuery table:
  /// <project_id>:export_evaluated_examples_<model_name>_<yyyy_MM_dd'T'HH_mm_ss_SSS'Z'>.evaluated_examples
  public var destinationBigqueryUri: Swift.String = Swift.String()

  /// If true and an export destination is specified, then the contents of the
  /// destination are overwritten. Otherwise, if the export destination already
  /// exists, then the export operation fails.
  public var overrideExistingTable: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExportEvaluatedDataItemsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportEvaluatedDataItemsConfig().with { $0.destinationBigqueryUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let destinationBigqueryUri = CodingKeys(stringValue: "destinationBigqueryUri")
    static let overrideExistingTable = CodingKeys(stringValue: "overrideExistingTable")

    static let _knownKeys: Set<Swift.String> = [
      "destinationBigqueryUri",
      "overrideExistingTable",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationBigqueryUri)
    {
      self.destinationBigqueryUri = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .overrideExistingTable) {
      self.overrideExistingTable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.destinationBigqueryUri, forKey: .destinationBigqueryUri)
    try container.encode(self.overrideExistingTable, forKey: .overrideExistingTable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.trainingjob.definition.ExportEvaluatedDataItemsConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
